Fix preflight scans
dell/karavi-topology pull request #149
Opened 2024-04-15 12:16 UTC by panigs7

# Description
Fix Preflight scans

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [X] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have inspected the Grafana dashboards to verify the data is displayed properly
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

Preflight scans passed:
![image](https://github.com/dell/karavi-topology/assets/92028646/025a1815-44f4-4a36-980d-6b890d446e6b)

2024-04-15 12:24 UTC, HarishH-DELL approved these changes

2024-04-15 12:30 UTC, gallacher requested changes
Please provide more details on why these changes are required in the description of the pull request.

2024-04-15 15:12 UTC, panigs7 commented
> Please provide more details on why these changes are required in the description of the pull request.

Done

2024-04-15 16:04 UTC, gallacher approved these changes

2024-04-17 09:31 UTC, prablr79 approved these changes

2024-04-17 09:32 UTC, merged